### ISSUE TITLE
Feature Request: Auto Scrollable Horizontal Cards

### ISSUE THREAD

**Issue by alok722** [fuxingloh/vue-horizontal-list#17]
Provide an option to make card group Scrollable by setting option to true or false.

**Comment by Draccano** [comment]
@fuxingloh will you provide this functionality?

**Comment by fuxingloh** [comment]
> @fuxingloh will you provide this functionality?

I assume Scrollable as in scrollbar? It's actually currently hidden with a css hack, not sure if how to proceed.

**Comment by Draccano** [comment]
I understand that and what about the drag functionality by mouse, similar issue it https://github.com/fuxingloh/vue-horizontal-list/issues/27

**Comment by alok722** [comment]
the auto scroll feature is implemented, you all can find it here: https://github.com/MiKr13/vue-horizontal-list-autoscroll

**Comment by Draccano** [comment]
> the auto scroll feature is implemented, you all can find it here: https://github.com/MiKr13/vue-horizontal-list-autoscroll

I have implemented startIndex and repeat option, if you have improvement, make fork and PR. It is better to improve one lib than do it separate.

**Comment by alok722** [comment]
> > the auto scroll feature is implemented, you all can find it here: https://github.com/MiKr13/vue-horizontal-list-autoscroll
> 
> I have implemented startIndex and repeat option, if you have improvement, make fork and PR. It is better to improve one lib than do it separate.

@mikr13 please do a PR to improve this lib

**Comment by MiKr13** [comment]
This package seemed inactive in terms of development that's why I created that seperate package because we needed the functionality in our code asap. No offense to the author of this project and I have provided due credit to him in my implementation but I think he can improve on Maintanence aspect.
@alok722 @Draccano @fuxingloh

**Comment by Draccano** [comment]
> This package seemed inactive in terms of development that's why I created that seperate package because we needed the functionality in our code asap. No offense to the author of this project and I have provided due credit to him in my implementation but I think he can improve on Maintanence aspect.
> My goal is to keep it updated with the requirements & new features when required.
> @alok722 @Draccano @fuxingloh 

It appeared inactive. However, the maintainer has merged my two pull requests in the last three days. 

You are right. The maintainer could more participate in the project. But still, I think he has enthusiasm and will work on it in the future 😀. This repo has potential. I had the same issue, needed fix dragging on mobile view for my private project so what I did was fix it by myself and then share it with the community if possible, @fuxingloh is open to new features and improvements. 😉

**Comment by fuxingloh** [comment]
Hello all!

I recently published another project called [Vue Horizontal](https://github.com/fuxingloh/vue-horizontal) that is another take on the horizontal layout with an ultra simple implementation that is extensible and moves the responsibility to the user rather than the library (for good reasons). With zero dependencies, 3 KB for CDN users it's built for your production needs.

End-to-end tested on real browser on each merge, SSG/SSR CI to make sure SEO never fails. Taken account into everything I know about web dev and horizontal layout, it might be useful repo to check out!

You can check out the project at https://github.com/fuxingloh/vue-horizontal.

```html
<vue-horizontal>
  <div class="item">
    <h3>HTML</h3>
    <p>Can be just any HTML declaration</p>
  </div>
  <section v-for="i in [0,1,2,3]" :key="i">
    <h3>{{ i }}</h3>
  </section>
  <section>
    <p>Structure your content however your like!</p>
  </section>
</vue-horizontal>
```

### Also documented
* https://vue-horizontal.fuxing.dev/others/autoplay
* https://vue-horizontal.fuxing.dev/design/scrollbar
* https://vue-horizontal.fuxing.dev/others/dragging and why it's a bad idea to do this

> Going to close this now! 😀
